version: '2'
services:

  postgres:
    image: postgres:9.6-alpine
    volumes:
        - ./docker/postgres:/docker-entrypoint-initdb.d
    environment:
        - POSTGRES_DB=dataprotection
    ports:
        - 5432:5432
  test:
    build:
      context: .
      dockerfile: dockerfile_test
    volumes:
        - .:/app
    links:
        - postgres
    depends_on:
        - postgres



